/* Editable fictional catalogue. Prices are illustrative GBP amounts in minor units.
 * Imagery, garment specifications, sizes and stock are design fixtures, not real inventory.
 * Changing currency requires changing prices too; no exchange-rate conversion is performed.
 */
window.VEXA = {
  brand: 'VEXA', currency: 'GBP', locale: 'en-GB',
  shipping: [{id:'standard',name:'Standard delivery',note:'Sample option · 4–6 working days',price:1200},{id:'express',name:'Express delivery',note:'Sample option · 1–2 working days',price:2200}],
  products: [
    {id:'foundation-hoodie',name:'Foundation Hoodie',category:'Hoodies',price:16000,image:'hoodie',tag:'01 / FOUNDATION',collection:'Foundation',new:true,description:'A considered silhouette. Heavyweight jersey, a generous hood and a dropped shoulder. Nothing added without a reason.',material:'Illustrative specification: 480 gsm cotton jersey, ribbed cuffs and hem.',fit:'Oversized, unisex fit. Sample garment measurements are available in the size guide.',sizes:['XS','S','M','L','XL'],stock:{XS:3,S:6,M:7,L:5,XL:0},colours:[{name:'Washed black',hex:'#282827',image:'hoodie'},{name:'Chalk',hex:'#c9c3b6',image:'hoodie-chalk'}]},
    {id:'signal-tee',name:'Signal T-Shirt',category:'T-Shirts',price:8500,image:'tee',tag:'02 / FOUNDATION',collection:'Foundation',new:true,description:'Quiet from a distance. A box-cut everyday T-shirt with a compact neckline and a substantial hand feel.',material:'Illustrative specification: 260 gsm cotton jersey; ribbed collar.',fit:'Boxy, unisex fit. Take your usual size for the intended silhouette.',sizes:['XS','S','M','L','XL'],stock:{XS:4,S:8,M:8,L:4,XL:3},colours:[{name:'Washed black',hex:'#282827',image:'tee'},{name:'Chalk',hex:'#c9c3b6',image:'tee-chalk'}]},
    {id:'tactical-cargo',name:'Tactical Cargo',category:'Trousers',price:18000,image:'cargo',tag:'03 / UTILITY',collection:'Utility',new:true,description:'Built around movement. A relaxed leg, considered pocket placement and adjustable detailing.',material:'Illustrative specification: cotton twill with utility pocket construction.',fit:'Relaxed leg. Sizes shown are illustrative waist sizes in inches.',sizes:['28','30','32','34','36'],stock:{28:2,30:6,32:6,34:4,36:0},colours:[{name:'Charcoal',hex:'#555551',image:'cargo'}]},
    {id:'archive-varsity',name:'Archive Varsity',category:'Outerwear',price:26000,image:'varsity',tag:'04 / ARCHIVE',collection:'Archive',new:true,description:'A familiar shape, reconsidered. A structured body, contrast details and room for the layers underneath.',material:'Illustrative specification: wool-blend body, lined interior and ribbed trims.',fit:'Relaxed, unisex fit. Size up for heavier layering.',sizes:['XS','S','M','L','XL'],stock:{XS:2,S:3,M:4,L:3,XL:1},colours:[{name:'Washed black',hex:'#282827',image:'varsity'}]},
    {id:'distorted-denim',name:'Distorted Denim',category:'Trousers',price:17000,image:'denim',tag:'05 / ARCHIVE',collection:'Archive',new:false,description:'Faded character. Straight-leg denim with a worn-in finish and deliberate distressing.',material:'Illustrative specification: rigid cotton denim with a washed finish.',fit:'Straight, relaxed leg. Sample waist sizes are shown in inches.',sizes:['28','30','32','34','36'],stock:{28:2,30:3,32:5,34:4,36:2},colours:[{name:'Charcoal',hex:'#555551',image:'denim'}]},
    {id:'core-longsleeve',name:'Core Longsleeve',category:'T-Shirts',price:9500,image:'longsleeve',tag:'06 / FOUNDATION',collection:'Foundation',new:false,description:'The first layer, made to stand alone. A clean long-sleeved silhouette with a relaxed drape.',material:'Illustrative specification: heavyweight cotton jersey, ribbed neckline.',fit:'Relaxed, unisex fit. Take your usual size.',sizes:['XS','S','M','L','XL'],stock:{XS:0,S:4,M:6,L:5,XL:3},colours:[{name:'Washed black',hex:'#282827',image:'longsleeve'},{name:'Chalk',hex:'#c9c3b6',image:'longsleeve-chalk'}]},
    {id:'utility-beanie',name:'Utility Beanie',category:'Accessories',price:6000,image:'beanie',tag:'07 / UTILITY',collection:'Utility',new:false,description:'A compact rib knit. A turned-up cuff. An easy finish to the everyday uniform.',material:'Illustrative specification: cotton-blend rib knit.',fit:'One size. Sample sizing only.',sizes:['One size'],stock:{'One size':8},colours:[{name:'Washed black',hex:'#282827',image:'beanie'}]},
    {id:'studio-cap',name:'Studio Cap',category:'Accessories',price:5500,image:'cap',tag:'08 / FOUNDATION',collection:'Foundation',new:false,description:'An understated six-panel cap with an adjustable fit and an embroidered studio signature.',material:'Illustrative specification: cotton twill; adjustable back strap.',fit:'One size, adjustable. Sample sizing only.',sizes:['One size'],stock:{'One size':0},colours:[{name:'Washed black',hex:'#282827',image:'cap'}]}
  ]
};
